### ISSUE TITLE
Issue with warnings

### ISSUE THREAD

**Issue by bcappa** [tvwenger/bayes_spec#18]
Hello,

When I run the following code from the tutorial:

```
from bayes_spec.plots import plot_pair

# available parameter attributes:
print("baseline_freeRVs", model.baseline_freeRVs)
print("baseline_deterministics", model.baseline_deterministics)
print("cloud_freeRVs", model.cloud_freeRVs)
print("cloud_deterministics", model.cloud_deterministics)
print("hyper_freeRVs", model.hyper_freeRVs)
print("hyper_deterministics", model.hyper_deterministics)

var_names = model.cloud_deterministics
_ = plot_pair(
    prior.prior, # samples
    var_names, # var_names to plot
    labeller=model.labeller, # label manager
)
```

I get the following error:

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> /tmp/ipykernel_23905/695882820.py in <module>
>      10 
>      11 var_names = model.cloud_deterministics
> ---> 12 _ = plot_pair(
>      13     prior.prior, # samples
>      14     var_names, # var_names to plot
> 
> ~/.local/lib/python3.10/site-packages/bayes_spec/plots.py in plot_pair(trace, var_names, labeller)
>     113     textsize = int(np.sqrt(size)) + 8
>     114     with az.rc_context(rc={"plot.max_subplots": None}):
> --> 115         with warnings.catch_warnings(action="ignore"):
>     116             axes = az.plot_pair(
>     117                 trace,
> 
> TypeError: catch_warnings.__init__() got an unexpected keyword argument 'action'

I updated my version of python to version 3.11.7 and this resolved.

**Comment by tvwenger** [comment]
Thanks for the report!
