### ISSUE TITLE
[JOSS Review] Installation

### ISSUE THREAD

**Issue by kbwestfall** [tvwenger/bayes_spec#37]
I personally don't use conda, but I can confirm the code installs using both virtualenv and conda.  Interestingly, I get the following warning when I don't use conda. `WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.`

**Comment by tvwenger** [comment]
@kbwestfall Thanks for testing installation in `virtualenv`. Indeed, those warnings are a known issue when you don't use `conda` to install `pytensor`. See: https://discourse.pymc.io/t/warning-pytensor-tensor-blas/13373
