### ISSUE TITLE
[JOSS Review] `ipywidgets` dependency

### ISSUE THREAD

**Issue by kbwestfall** [tvwenger/bayes_spec#39]
The documentation is generally excellent.

I only tested the `basic_tutorial.ipynb` file, but I can confirm it ran successfully and the outputs are virtually identical to what's shown in the documentation.

One note that may just be an artifact of me running the notebook in VS Code:  I had to install ipykernel to get the code to execute, and some of the outputs wouldn't display without installing `ipywidgets`.

**Comment by tvwenger** [comment]
Fixed by https://github.com/tvwenger/bayes_spec/pull/49
