### ISSUE TITLE
[JOSS Review] Does `jax` and `jaxlib` need to be pinned?

### ISSUE THREAD

**Issue by ConorMacBride** [tvwenger/bayes_spec#41]
`jax` and `jaxlib` are pinned to specific versions. They don't seem to be direct dependencies of `bayes_spec`, but come in via `blackjax`. Were these pinned to fix a particular bug? When I `pip install -e .` with `jax` and `jaxlib` removed from `requirements.txt`, all the tests pass.

https://github.com/tvwenger/bayes_spec/blob/b07721f6ad6e29b16dccf06865556da0060cb24a/requirements.txt#L11-L12

cc https://github.com/openjournals/joss-reviews/issues/7201

**Comment by tvwenger** [comment]
Indeed these dependencies were pinned due to an upstream bug

https://github.com/conda-forge/jaxlib-feedstock/issues/277

It looks like that bug has been resolved, so I will unpin these dependencies.

**Comment by tvwenger** [comment]
Fixed by https://github.com/tvwenger/bayes_spec/pull/49
