### ISSUE TITLE
[JOSS Review] Set docs website default version to `stable`

### ISSUE THREAD

**Issue by ConorMacBride** [tvwenger/bayes_spec#44]
The documentation website seems to have its default version set to `latest` (`main` branch docs). It might be best to change it to the `stable` version (most recent tag docs) so users are shown the docs for the most recent version they can get from `pip install bayes_spec`.

**Comment by tvwenger** [comment]
Thanks for the suggestion! I've updated the README and changed the default version on readthedocs to `stable`.

**Comment by tvwenger** [comment]
Fixed by https://github.com/tvwenger/bayes_spec/pull/48
